# Generated by Django 3.2.15 on 2022-08-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(choices=[('', 'Selecione um assunto'), ('descontos', 'Descontos'), ('consultoria', 'Consultoria'), ('freelance', 'Freelance'), ('elogios', 'Elogios'), ('reclamações', 'Reclamações'), ('outros', 'Outros')], default='', max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('mensagem', models.CharField(max_length=100)),
            ],
        ),
    ]
