# Generated by Django 3.2.15 on 2022-08-14 02:53

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='teste',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='conteudo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
