# Generated by Django 3.2.15 on 2022-08-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220813_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='teste',
        ),
    ]
