# Generated by Django 3.2.15 on 2022-08-21 00:36

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_teste'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog/'),
        ),
        migrations.AddField(
            model_name='post',
            name='resumo',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
